name: petlove_talents_case_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pip=23.1.2
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - ipykernel=6.22.0